In [ ]:
#prgm for creating a
import numpy as np
import time
num_arr=np.random.randint(1,51,size=(5,5)) #taking random numbers from 1 to 50 to an array of size 5,5
print(num_arr)
mean_val=num_arr.mean()#finding the mean of the array
rsum=num_arr.sum(axis=1)#finding the sum of each row and storing it into an array

print (f"sum of each row is {rsum}")
maxsum=rsum.max()#finding the maximum value from array of row total
print(f"Maximum_eachRow   {maxsum}")

num_arr[num_arr>mean_val]=0 #replacing elements whose value more tha mean with 0
print("After replacing_mean"  )
time.sleep(1)
print(num_arr)

[[46 15 33 29  4]
 [46 50 30 10 47]
 [39  2  6 43  1]
 [37 29 21 25 37]
 [ 7 29 20 37  5]]
sum of each row is [127 183  91 149  98]
Maximum_eachRow   183
After replacing_mean
[[ 0 15  0  0  4]
 [ 0  0  0 10  0]
 [ 0  2  6  0  1]
 [ 0  0 21 25  0]
 [ 7  0 20  0  5]]
